<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onnx.proto3

namespace Onnx\TypeProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * map<K,V>
 *
 * Generated from protobuf message <code>onnx.TypeProto.Map</code>
 */
class Map extends \Google\Protobuf\Internal\Message
{
    /**
     * This field MUST have a valid TensorProto.DataType value
     * This field MUST be present for this version of the IR.
     * This field MUST refer to an integral type ([U]INT{8|16|32|64}) or STRING
     *
     * Generated from protobuf field <code>int32 key_type = 1;</code>
     */
    protected $key_type = 0;
    /**
     * This field MUST be present for this version of the IR.
     *
     * Generated from protobuf field <code>.onnx.TypeProto value_type = 2;</code>
     */
    protected $value_type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $key_type
     *           This field MUST have a valid TensorProto.DataType value
     *           This field MUST be present for this version of the IR.
     *           This field MUST refer to an integral type ([U]INT{8|16|32|64}) or STRING
     *     @type \Onnx\TypeProto $value_type
     *           This field MUST be present for this version of the IR.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Onnx::initOnce();
        parent::__construct($data);
    }

    /**
     * This field MUST have a valid TensorProto.DataType value
     * This field MUST be present for this version of the IR.
     * This field MUST refer to an integral type ([U]INT{8|16|32|64}) or STRING
     *
     * Generated from protobuf field <code>int32 key_type = 1;</code>
     * @return int
     */
    public function getKeyType()
    {
        return $this->key_type;
    }

    /**
     * This field MUST have a valid TensorProto.DataType value
     * This field MUST be present for this version of the IR.
     * This field MUST refer to an integral type ([U]INT{8|16|32|64}) or STRING
     *
     * Generated from protobuf field <code>int32 key_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setKeyType($var)
    {
        GPBUtil::checkInt32($var);
        $this->key_type = $var;

        return $this;
    }

    /**
     * This field MUST be present for this version of the IR.
     *
     * Generated from protobuf field <code>.onnx.TypeProto value_type = 2;</code>
     * @return \Onnx\TypeProto|null
     */
    public function getValueType()
    {
        return $this->value_type;
    }

    public function hasValueType()
    {
        return isset($this->value_type);
    }

    public function clearValueType()
    {
        unset($this->value_type);
    }

    /**
     * This field MUST be present for this version of the IR.
     *
     * Generated from protobuf field <code>.onnx.TypeProto value_type = 2;</code>
     * @param \Onnx\TypeProto $var
     * @return $this
     */
    public function setValueType($var)
    {
        GPBUtil::checkMessage($var, \Onnx\TypeProto::class);
        $this->value_type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Map::class, \Onnx\TypeProto_Map::class);

