<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onnx.proto3

namespace Onnx\TypeProto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * wrapper for Tensor, Sequence, or Map
 *
 * Generated from protobuf message <code>onnx.TypeProto.Optional</code>
 */
class Optional extends \Google\Protobuf\Internal\Message
{
    /**
     * The type and optional shape of the element wrapped.
     * This field MUST be present for this version of the IR.
     * Possible values correspond to OptionalProto.DataType enum
     *
     * Generated from protobuf field <code>.onnx.TypeProto elem_type = 1;</code>
     */
    protected $elem_type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Onnx\TypeProto $elem_type
     *           The type and optional shape of the element wrapped.
     *           This field MUST be present for this version of the IR.
     *           Possible values correspond to OptionalProto.DataType enum
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Onnx::initOnce();
        parent::__construct($data);
    }

    /**
     * The type and optional shape of the element wrapped.
     * This field MUST be present for this version of the IR.
     * Possible values correspond to OptionalProto.DataType enum
     *
     * Generated from protobuf field <code>.onnx.TypeProto elem_type = 1;</code>
     * @return \Onnx\TypeProto|null
     */
    public function getElemType()
    {
        return $this->elem_type;
    }

    public function hasElemType()
    {
        return isset($this->elem_type);
    }

    public function clearElemType()
    {
        unset($this->elem_type);
    }

    /**
     * The type and optional shape of the element wrapped.
     * This field MUST be present for this version of the IR.
     * Possible values correspond to OptionalProto.DataType enum
     *
     * Generated from protobuf field <code>.onnx.TypeProto elem_type = 1;</code>
     * @param \Onnx\TypeProto $var
     * @return $this
     */
    public function setElemType($var)
    {
        GPBUtil::checkMessage($var, \Onnx\TypeProto::class);
        $this->elem_type = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Optional::class, \Onnx\TypeProto_Optional::class);

