<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onnx.proto3

namespace Onnx;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Graphs
 * A graph defines the computational logic of a model and is comprised of a parameterized
 * list of nodes that form a directed acyclic graph based on their inputs and outputs.
 * This is the equivalent of the "network" or "graph" in many deep learning
 * frameworks.
 *
 * Generated from protobuf message <code>onnx.GraphProto</code>
 */
class GraphProto extends \Google\Protobuf\Internal\Message
{
    /**
     * The nodes in the graph, sorted topologically.
     *
     * Generated from protobuf field <code>repeated .onnx.NodeProto node = 1;</code>
     */
    private $node;
    /**
     * The name of the graph.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     */
    protected $name = '';
    /**
     * A list of named tensor values, used to specify constant inputs of the graph.
     * Each initializer (both TensorProto as well SparseTensorProto) MUST have a name.
     * The name MUST be unique across both initializer and sparse_initializer,
     * but the name MAY also appear in the input list.
     *
     * Generated from protobuf field <code>repeated .onnx.TensorProto initializer = 5;</code>
     */
    private $initializer;
    /**
     * Initializers (see above) stored in sparse format.
     *
     * Generated from protobuf field <code>repeated .onnx.SparseTensorProto sparse_initializer = 15;</code>
     */
    private $sparse_initializer;
    /**
     * A human-readable documentation for this graph. Markdown is allowed.
     *
     * Generated from protobuf field <code>string doc_string = 10;</code>
     */
    protected $doc_string = '';
    /**
     * The inputs and outputs of the graph.
     *
     * Generated from protobuf field <code>repeated .onnx.ValueInfoProto input = 11;</code>
     */
    private $input;
    /**
     * Generated from protobuf field <code>repeated .onnx.ValueInfoProto output = 12;</code>
     */
    private $output;
    /**
     * Information for the values in the graph. The ValueInfoProto.name's
     * must be distinct. It is optional for a value to appear in value_info list.
     *
     * Generated from protobuf field <code>repeated .onnx.ValueInfoProto value_info = 13;</code>
     */
    private $value_info;
    /**
     * This field carries information to indicate the mapping among a tensor and its
     * quantization parameter tensors. For example:
     * For tensor 'a', it may have {'SCALE_TENSOR', 'a_scale'} and {'ZERO_POINT_TENSOR', 'a_zero_point'} annotated,
     * which means, tensor 'a_scale' and tensor 'a_zero_point' are scale and zero point of tensor 'a' in the model.
     *
     * Generated from protobuf field <code>repeated .onnx.TensorAnnotation quantization_annotation = 14;</code>
     */
    private $quantization_annotation;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Onnx\NodeProto>|\Google\Protobuf\Internal\RepeatedField $node
     *           The nodes in the graph, sorted topologically.
     *     @type string $name
     *           The name of the graph.
     *     @type array<\Onnx\TensorProto>|\Google\Protobuf\Internal\RepeatedField $initializer
     *           A list of named tensor values, used to specify constant inputs of the graph.
     *           Each initializer (both TensorProto as well SparseTensorProto) MUST have a name.
     *           The name MUST be unique across both initializer and sparse_initializer,
     *           but the name MAY also appear in the input list.
     *     @type array<\Onnx\SparseTensorProto>|\Google\Protobuf\Internal\RepeatedField $sparse_initializer
     *           Initializers (see above) stored in sparse format.
     *     @type string $doc_string
     *           A human-readable documentation for this graph. Markdown is allowed.
     *     @type array<\Onnx\ValueInfoProto>|\Google\Protobuf\Internal\RepeatedField $input
     *           The inputs and outputs of the graph.
     *     @type array<\Onnx\ValueInfoProto>|\Google\Protobuf\Internal\RepeatedField $output
     *     @type array<\Onnx\ValueInfoProto>|\Google\Protobuf\Internal\RepeatedField $value_info
     *           Information for the values in the graph. The ValueInfoProto.name's
     *           must be distinct. It is optional for a value to appear in value_info list.
     *     @type array<\Onnx\TensorAnnotation>|\Google\Protobuf\Internal\RepeatedField $quantization_annotation
     *           This field carries information to indicate the mapping among a tensor and its
     *           quantization parameter tensors. For example:
     *           For tensor 'a', it may have {'SCALE_TENSOR', 'a_scale'} and {'ZERO_POINT_TENSOR', 'a_zero_point'} annotated,
     *           which means, tensor 'a_scale' and tensor 'a_zero_point' are scale and zero point of tensor 'a' in the model.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Onnx::initOnce();
        parent::__construct($data);
    }

    /**
     * The nodes in the graph, sorted topologically.
     *
     * Generated from protobuf field <code>repeated .onnx.NodeProto node = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNode()
    {
        return $this->node;
    }

    /**
     * The nodes in the graph, sorted topologically.
     *
     * Generated from protobuf field <code>repeated .onnx.NodeProto node = 1;</code>
     * @param array<\Onnx\NodeProto>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNode($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Onnx\NodeProto::class);
        $this->node = $arr;

        return $this;
    }

    /**
     * The name of the graph.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * The name of the graph.
     *
     * Generated from protobuf field <code>string name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * A list of named tensor values, used to specify constant inputs of the graph.
     * Each initializer (both TensorProto as well SparseTensorProto) MUST have a name.
     * The name MUST be unique across both initializer and sparse_initializer,
     * but the name MAY also appear in the input list.
     *
     * Generated from protobuf field <code>repeated .onnx.TensorProto initializer = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInitializer()
    {
        return $this->initializer;
    }

    /**
     * A list of named tensor values, used to specify constant inputs of the graph.
     * Each initializer (both TensorProto as well SparseTensorProto) MUST have a name.
     * The name MUST be unique across both initializer and sparse_initializer,
     * but the name MAY also appear in the input list.
     *
     * Generated from protobuf field <code>repeated .onnx.TensorProto initializer = 5;</code>
     * @param array<\Onnx\TensorProto>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInitializer($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Onnx\TensorProto::class);
        $this->initializer = $arr;

        return $this;
    }

    /**
     * Initializers (see above) stored in sparse format.
     *
     * Generated from protobuf field <code>repeated .onnx.SparseTensorProto sparse_initializer = 15;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSparseInitializer()
    {
        return $this->sparse_initializer;
    }

    /**
     * Initializers (see above) stored in sparse format.
     *
     * Generated from protobuf field <code>repeated .onnx.SparseTensorProto sparse_initializer = 15;</code>
     * @param array<\Onnx\SparseTensorProto>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSparseInitializer($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Onnx\SparseTensorProto::class);
        $this->sparse_initializer = $arr;

        return $this;
    }

    /**
     * A human-readable documentation for this graph. Markdown is allowed.
     *
     * Generated from protobuf field <code>string doc_string = 10;</code>
     * @return string
     */
    public function getDocString()
    {
        return $this->doc_string;
    }

    /**
     * A human-readable documentation for this graph. Markdown is allowed.
     *
     * Generated from protobuf field <code>string doc_string = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setDocString($var)
    {
        GPBUtil::checkString($var, True);
        $this->doc_string = $var;

        return $this;
    }

    /**
     * The inputs and outputs of the graph.
     *
     * Generated from protobuf field <code>repeated .onnx.ValueInfoProto input = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     * The inputs and outputs of the graph.
     *
     * Generated from protobuf field <code>repeated .onnx.ValueInfoProto input = 11;</code>
     * @param array<\Onnx\ValueInfoProto>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInput($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Onnx\ValueInfoProto::class);
        $this->input = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .onnx.ValueInfoProto output = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutput()
    {
        return $this->output;
    }

    /**
     * Generated from protobuf field <code>repeated .onnx.ValueInfoProto output = 12;</code>
     * @param array<\Onnx\ValueInfoProto>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutput($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Onnx\ValueInfoProto::class);
        $this->output = $arr;

        return $this;
    }

    /**
     * Information for the values in the graph. The ValueInfoProto.name's
     * must be distinct. It is optional for a value to appear in value_info list.
     *
     * Generated from protobuf field <code>repeated .onnx.ValueInfoProto value_info = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getValueInfo()
    {
        return $this->value_info;
    }

    /**
     * Information for the values in the graph. The ValueInfoProto.name's
     * must be distinct. It is optional for a value to appear in value_info list.
     *
     * Generated from protobuf field <code>repeated .onnx.ValueInfoProto value_info = 13;</code>
     * @param array<\Onnx\ValueInfoProto>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setValueInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Onnx\ValueInfoProto::class);
        $this->value_info = $arr;

        return $this;
    }

    /**
     * This field carries information to indicate the mapping among a tensor and its
     * quantization parameter tensors. For example:
     * For tensor 'a', it may have {'SCALE_TENSOR', 'a_scale'} and {'ZERO_POINT_TENSOR', 'a_zero_point'} annotated,
     * which means, tensor 'a_scale' and tensor 'a_zero_point' are scale and zero point of tensor 'a' in the model.
     *
     * Generated from protobuf field <code>repeated .onnx.TensorAnnotation quantization_annotation = 14;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getQuantizationAnnotation()
    {
        return $this->quantization_annotation;
    }

    /**
     * This field carries information to indicate the mapping among a tensor and its
     * quantization parameter tensors. For example:
     * For tensor 'a', it may have {'SCALE_TENSOR', 'a_scale'} and {'ZERO_POINT_TENSOR', 'a_zero_point'} annotated,
     * which means, tensor 'a_scale' and tensor 'a_zero_point' are scale and zero point of tensor 'a' in the model.
     *
     * Generated from protobuf field <code>repeated .onnx.TensorAnnotation quantization_annotation = 14;</code>
     * @param array<\Onnx\TensorAnnotation>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setQuantizationAnnotation($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Onnx\TensorAnnotation::class);
        $this->quantization_annotation = $arr;

        return $this;
    }

}

