<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onnx.proto3

namespace Onnx;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Nodes
 * Computation graphs are made up of a DAG of nodes, which represent what is
 * commonly called a "layer" or "pipeline stage" in machine learning frameworks.
 * For example, it can be a node of type "Conv" that takes in an image, a filter
 * tensor and a bias tensor, and produces the convolved output.
 *
 * Generated from protobuf message <code>onnx.NodeProto</code>
 */
class NodeProto extends \Google\Protobuf\Internal\Message
{
    /**
     * namespace Value
     *
     * Generated from protobuf field <code>repeated string input = 1;</code>
     */
    private $input;
    /**
     * namespace Value
     *
     * Generated from protobuf field <code>repeated string output = 2;</code>
     */
    private $output;
    /**
     * An optional identifier for this node in a graph.
     * This field MAY be absent in ths version of the IR.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     */
    protected $name = '';
    /**
     * The symbolic identifier of the Operator to execute.
     *
     * Generated from protobuf field <code>string op_type = 4;</code>
     */
    protected $op_type = '';
    /**
     * The domain of the OperatorSet that specifies the operator named by op_type.
     *
     * Generated from protobuf field <code>string domain = 7;</code>
     */
    protected $domain = '';
    /**
     * Additional named attributes.
     *
     * Generated from protobuf field <code>repeated .onnx.AttributeProto attribute = 5;</code>
     */
    private $attribute;
    /**
     * A human-readable documentation for this node. Markdown is allowed.
     *
     * Generated from protobuf field <code>string doc_string = 6;</code>
     */
    protected $doc_string = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $input
     *           namespace Value
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $output
     *           namespace Value
     *     @type string $name
     *           An optional identifier for this node in a graph.
     *           This field MAY be absent in ths version of the IR.
     *     @type string $op_type
     *           The symbolic identifier of the Operator to execute.
     *     @type string $domain
     *           The domain of the OperatorSet that specifies the operator named by op_type.
     *     @type array<\Onnx\AttributeProto>|\Google\Protobuf\Internal\RepeatedField $attribute
     *           Additional named attributes.
     *     @type string $doc_string
     *           A human-readable documentation for this node. Markdown is allowed.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Onnx::initOnce();
        parent::__construct($data);
    }

    /**
     * namespace Value
     *
     * Generated from protobuf field <code>repeated string input = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     * namespace Value
     *
     * Generated from protobuf field <code>repeated string input = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInput($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->input = $arr;

        return $this;
    }

    /**
     * namespace Value
     *
     * Generated from protobuf field <code>repeated string output = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutput()
    {
        return $this->output;
    }

    /**
     * namespace Value
     *
     * Generated from protobuf field <code>repeated string output = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutput($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->output = $arr;

        return $this;
    }

    /**
     * An optional identifier for this node in a graph.
     * This field MAY be absent in ths version of the IR.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * An optional identifier for this node in a graph.
     * This field MAY be absent in ths version of the IR.
     *
     * Generated from protobuf field <code>string name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * The symbolic identifier of the Operator to execute.
     *
     * Generated from protobuf field <code>string op_type = 4;</code>
     * @return string
     */
    public function getOpType()
    {
        return $this->op_type;
    }

    /**
     * The symbolic identifier of the Operator to execute.
     *
     * Generated from protobuf field <code>string op_type = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOpType($var)
    {
        GPBUtil::checkString($var, True);
        $this->op_type = $var;

        return $this;
    }

    /**
     * The domain of the OperatorSet that specifies the operator named by op_type.
     *
     * Generated from protobuf field <code>string domain = 7;</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * The domain of the OperatorSet that specifies the operator named by op_type.
     *
     * Generated from protobuf field <code>string domain = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain = $var;

        return $this;
    }

    /**
     * Additional named attributes.
     *
     * Generated from protobuf field <code>repeated .onnx.AttributeProto attribute = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAttribute()
    {
        return $this->attribute;
    }

    /**
     * Additional named attributes.
     *
     * Generated from protobuf field <code>repeated .onnx.AttributeProto attribute = 5;</code>
     * @param array<\Onnx\AttributeProto>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAttribute($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Onnx\AttributeProto::class);
        $this->attribute = $arr;

        return $this;
    }

    /**
     * A human-readable documentation for this node. Markdown is allowed.
     *
     * Generated from protobuf field <code>string doc_string = 6;</code>
     * @return string
     */
    public function getDocString()
    {
        return $this->doc_string;
    }

    /**
     * A human-readable documentation for this node. Markdown is allowed.
     *
     * Generated from protobuf field <code>string doc_string = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDocString($var)
    {
        GPBUtil::checkString($var, True);
        $this->doc_string = $var;

        return $this;
    }

}

