<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onnx.proto3

namespace Onnx;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Operator Sets
 * OperatorSets are uniquely identified by a (domain, opset_version) pair.
 *
 * Generated from protobuf message <code>onnx.OperatorSetIdProto</code>
 */
class OperatorSetIdProto extends \Google\Protobuf\Internal\Message
{
    /**
     * The domain of the operator set being identified.
     * The empty string ("") or absence of this field implies the operator
     * set that is defined as part of the ONNX specification.
     * This field MUST be present in this version of the IR when referring to any other operator set.
     *
     * Generated from protobuf field <code>string domain = 1;</code>
     */
    protected $domain = '';
    /**
     * The version of the operator set being identified.
     * This field MUST be present in this version of the IR.
     *
     * Generated from protobuf field <code>int64 version = 2;</code>
     */
    protected $version = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $domain
     *           The domain of the operator set being identified.
     *           The empty string ("") or absence of this field implies the operator
     *           set that is defined as part of the ONNX specification.
     *           This field MUST be present in this version of the IR when referring to any other operator set.
     *     @type int|string $version
     *           The version of the operator set being identified.
     *           This field MUST be present in this version of the IR.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Onnx::initOnce();
        parent::__construct($data);
    }

    /**
     * The domain of the operator set being identified.
     * The empty string ("") or absence of this field implies the operator
     * set that is defined as part of the ONNX specification.
     * This field MUST be present in this version of the IR when referring to any other operator set.
     *
     * Generated from protobuf field <code>string domain = 1;</code>
     * @return string
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * The domain of the operator set being identified.
     * The empty string ("") or absence of this field implies the operator
     * set that is defined as part of the ONNX specification.
     * This field MUST be present in this version of the IR when referring to any other operator set.
     *
     * Generated from protobuf field <code>string domain = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDomain($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain = $var;

        return $this;
    }

    /**
     * The version of the operator set being identified.
     * This field MUST be present in this version of the IR.
     *
     * Generated from protobuf field <code>int64 version = 2;</code>
     * @return int|string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * The version of the operator set being identified.
     * This field MUST be present in this version of the IR.
     *
     * Generated from protobuf field <code>int64 version = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkInt64($var);
        $this->version = $var;

        return $this;
    }

}

