<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onnx.proto3

namespace Onnx;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Defines a tensor shape. A dimension can be either an integer value
 * or a symbolic variable. A symbolic variable represents an unknown
 * dimension.
 *
 * Generated from protobuf message <code>onnx.TensorShapeProto</code>
 */
class TensorShapeProto extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .onnx.TensorShapeProto.Dimension dim = 1;</code>
     */
    private $dim;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Onnx\TensorShapeProto\Dimension>|\Google\Protobuf\Internal\RepeatedField $dim
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Onnx::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .onnx.TensorShapeProto.Dimension dim = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDim()
    {
        return $this->dim;
    }

    /**
     * Generated from protobuf field <code>repeated .onnx.TensorShapeProto.Dimension dim = 1;</code>
     * @param array<\Onnx\TensorShapeProto\Dimension>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDim($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Onnx\TensorShapeProto\Dimension::class);
        $this->dim = $arr;

        return $this;
    }

}

