<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: onnx.proto3

namespace Onnx;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Defines information on value, including the name, the type, and
 * the shape of the value.
 *
 * Generated from protobuf message <code>onnx.ValueInfoProto</code>
 */
class ValueInfoProto extends \Google\Protobuf\Internal\Message
{
    /**
     * This field MUST be present in this version of the IR.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * This field MUST be present in this version of the IR for
     * inputs and outputs of the top-level graph.
     *
     * Generated from protobuf field <code>.onnx.TypeProto type = 2;</code>
     */
    protected $type = null;
    /**
     * A human-readable documentation for this value. Markdown is allowed.
     *
     * Generated from protobuf field <code>string doc_string = 3;</code>
     */
    protected $doc_string = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           This field MUST be present in this version of the IR.
     *     @type \Onnx\TypeProto $type
     *           This field MUST be present in this version of the IR for
     *           inputs and outputs of the top-level graph.
     *     @type string $doc_string
     *           A human-readable documentation for this value. Markdown is allowed.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Onnx::initOnce();
        parent::__construct($data);
    }

    /**
     * This field MUST be present in this version of the IR.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * This field MUST be present in this version of the IR.
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * This field MUST be present in this version of the IR for
     * inputs and outputs of the top-level graph.
     *
     * Generated from protobuf field <code>.onnx.TypeProto type = 2;</code>
     * @return \Onnx\TypeProto|null
     */
    public function getType()
    {
        return $this->type;
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * This field MUST be present in this version of the IR for
     * inputs and outputs of the top-level graph.
     *
     * Generated from protobuf field <code>.onnx.TypeProto type = 2;</code>
     * @param \Onnx\TypeProto $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkMessage($var, \Onnx\TypeProto::class);
        $this->type = $var;

        return $this;
    }

    /**
     * A human-readable documentation for this value. Markdown is allowed.
     *
     * Generated from protobuf field <code>string doc_string = 3;</code>
     * @return string
     */
    public function getDocString()
    {
        return $this->doc_string;
    }

    /**
     * A human-readable documentation for this value. Markdown is allowed.
     *
     * Generated from protobuf field <code>string doc_string = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setDocString($var)
    {
        GPBUtil::checkString($var, True);
        $this->doc_string = $var;

        return $this;
    }

}

